### ISSUE TITLE
Allow update of package list file

### ISSUE THREAD

**Issue by randycoulman** [lee-dohm/package-sync#15]
I really appreciate this package.  Thanks for creating it!

As I work with Atom, I'll install some new packages to improve my workflow.  I'd then like an easy way to update my `packages.cson` file with the newly-installed packages.  `create-package-list` only generates a `packages.cson` file if there isn't one already.  If I want to update my list of packages, I have to delete my old `packages.cson` and then use `create-package-list` again to re-create it.

An `update-package-list` command would simplify this workflow.

**Comment by lee-dohm** [comment]
Fixed in v1.0.0
