### ISSUE TITLE
Clarify how to run package-sync commands

### ISSUE THREAD

**Issue by rnsell** [lee-dohm/package-sync#16]
Hello,

I'm a little new to Atom, and this might help out other beginners as well. I was hoping someone could explain how to run the commands specified in the README and maybe update the README from the perspective of someone who might only know to interact through the gui.

**Comment by lee-dohm** [comment]
I'll see what I can add. The simple answer though is that you can run most Atom commands (including the package-sync commands) through the Command Palette which you can activate with <kbd>Cmd+Shift+P</kbd> on OS X or <kbd>Ctrl+Shift+P</kbd> on other platforms.

**Comment by Bluestin** [comment]
Thank you
