### ISSUE TITLE
Sync through the Github account

### ISSUE THREAD

**Issue by xavierfoucrier** [lee-dohm/package-sync#30]
It would be very cool to sync packages between computers just by login with our Github account to Atom. Just an idea.

**Comment by lee-dohm** [comment]
Thanks for the suggestion. Doing something like that is a bit beyond the scope of what's intended for this project since it would need an accompanying server-side implementation somewhere.

**Comment by xavierfoucrier** [comment]
Yep. Agree with that. Thanks for the reply 😉
